[package]
name = "frontend"
version = "0.1.0"
authors = ["Sam Toth <sam@toth.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.16"
wasm-bindgen = "0.2"